version: '3.8'
volumes:
  static:

networks:
  movies_network:
    driver: bridge

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: movies-elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - USE_SSL=false
    restart: unless-stopped
    networks:
      - movies_network
    depends_on:
      - postgres
    ports:
      - "9200:9200"

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.7.0
    environment:
      - ELASTICSEARCH_HOSTS=http://movies-elasticsearch:9200
    networks:
      - movies_network
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  redis:
    container_name: redis_container
    image: redis:6.2.6
    ports:
      - "6379:6379"
    networks:
      - movies_network

  async_api:
    container_name: async_api
    build:
      context: src
    restart: always
    depends_on:
      - elasticsearch
      - redis
    ports:
      - "8000:8000"
    env_file:
      - src/core/.env
    networks:
      - movies_network