version: '3.8'
volumes:
  postgres_data:

services:

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
      - .docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./etl/postgres_to_es/movies_dmp.sql:/docker-entrypoint-initdb.d/movies_dmp.sql
    environment:
      POSTGRES_DB: movies_database
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123qwe

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - USE_SSL=false
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "9200"

  etl:
    container_name: etl
    build:
      context: .
      dockerfile: etl/postgres_to_es/Dockerfile
    env_file:
      - .env
      - .docker.env
    restart: unless-stopped
    depends_on:
      - elasticsearch
