version: '3.8'
volumes:
  static:
  postgres_data:

services:

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - ./fastapi-solution/src/core/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./fastapi-solution/src/etl/postgres_to_es/movies_dmp.sql:/docker-entrypoint-initdb.d/movies_dmp.sql

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - USE_SSL=false
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "9200:9200"

  etl:
    container_name: etl
    build:
      context: .
      dockerfile: ./fastapi-solution/src/etl/postgres_to_es/Dockerfile
    env_file:
      - ./fastapi-solution/src/etl/postgres_to_es/.env
    restart: unless-stopped
    depends_on:
      - elasticsearch

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.7.0
    environment:
      - ELASTICSEARCH_HOSTS=http://movies-elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  redis:
    container_name: redis
    image: redis:6.2.6
    ports:
      - "6379:6379"

  async_api:
    container_name: async_api
    build:
      context: .
    restart: always
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - ./fastapi-solution/src/core/.env